#sonar.projectKey=clientIO_appmixer-connectors_AY7J_O6GZsPR2eThxIf0
sonar.projectKey=jirihofman_appmixer-connectors
sonar.organization=jirihofman
sonar.sources=src
sonar.test.exclusions=test,src/appmixer/**/artifacts/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# No actions on artifacts, tests and node_modules
sonar.exclusions=test/**,src/appmixer/**/artifacts/**,src/appmixer/utils/chat/chat.bundle.js,src/appmixer/**/node_modules/**
sonar.coverage.exclusions=node_modules/**,test/**,src/appmixer/**/artifacts/test/**